/*
    <SYNONYM>
    데이터베이스 객체에 대한 별칭, 동의어
    CREATE OR REPLACE [PUBLIC] SYNONYM
    - PUBLIC 명시하지 않으면 기본은 PRIVATE으로 설정됨
*/
-- 시노님 생성
CREATE OR REPLACE SYNONYM REGIONS FOR HR.REGIONS;
CREATE OR REPLACE PUBLIC SYNONYM P_REGIONS FOR HR.REGIONS;
-- => PUBLIC 권한을 따로 부여하지 않아도 JUNGANG(일반사용자)계정에서도 조회가 된다.?

-- 시노님 조회
SELECT * FROM REGIONS;

-- 시노님 제거
DROP PUBLIC SYNONYM P_REGIONS;

-- 권한 부여
GRANT SELECT ON REGIONS TO JUNGANG;
GRANT SELECT ON P_REGIONS TO PUBLIC;

-- 권한 회수
REVOKE SELECT ON REGIONS FROM JUNGANG;
REVOKE SELECT ON P_REGIONS FROM PUBLIC;

-- 사용자가 가진 권한을 확인
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'JUNGANG';

-- HR계정의 테이블이 가진 권한을 확인
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'HR';

-- 사용자가 가진 역할을 확인
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'JUNGANG';


/*
    JUNGANG 계정 워크시트에서 조회해봤던 내용 백업

    SELECT * FROM REGIONS;
    SELECT * FROM P_REGIONS;
    
    SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'JUNGANG';
    SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'JUNGANG';
    SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'HR';

*/









